name: Docker Image Build and Test

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Setup QEMU to build Docker image for multiple architectures (amd64, arm64...)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t onigiribot:latest .

    # Docker action for build and push could be used instead of last step,
    # but at the moment we are not pushing the image to any registry.
