name: Renovate
on:
  schedule:
    - cron: "0 2 * * *" # Runs at 2 AM daily
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
